level_1 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXX         T    XXXXX",
            "X       XX  XXXXX   XXXXX",
            "X       XX  XXXXX  XXXXX",
            "XP      XX  XXX        XX",
            "XXXXXX  XX  XXX T      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX        XXXX  XXXXX",
            "X  XXX  XXXXXXXXX   EXXXX",
            "X         XXXXXXX    XXXX",
            "X T                  XXXX",
            "XXX   XXXXXX     XXXXX TX",
            "XX     XXXXXXXX  XXXXX  X",
            "XXX    X                X",
            "XXX    X                X",
            "X      XXX  EXX     XXXXX",
            "XXXX       XXXX    XXXXXX",
            "XXXXXXX                 X",
            "XX   X   X              X",
            "XX   XXXXX          XXXXX",
            "XX    XXXX  XXXXXX  XXXXX",
            "XXT          XXXX       X",
            "XXX                    TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]
level_2 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X  XXXXXXX      E   XXXXX",
            "X  XXXXXXX    XXXX  XXXXX",
            "X       XX          XXXXX",
            "XP      XX  XXX        XX",
            "XX          XXX T      XX",
            "XXXXXX  XX  XXXXXX  XXXXX",
            "XXXXXX  XX    XXXX  XXXXX",
            "X  XXX      XXXXXX  XXXXX",
            "X  XXX  XXX           XXX",
            "X             XXXXXXXXXXX",
            "X T E            XXXXXXXX",
            "XXXXXXXXXXXX     XXXXXETX",
            "XXXXXXXXXXXXXXX  XXXXX  X",
            "XXX  XXXXXXXXXX         X",
            "XXX                     X",
            "XX          EXXX    TXXXX",
            "XXXXXXXXXX  XXXXXXXXXXXXX",
            "XXXXXXXXXX       X      X",
            "XX   XXXXX              X",
            "XX   XXXX      XXX  XXXXX",
            "XX    XXX    XXXXX  XXXXX",
            "XXT          XXXX       X",
            "XXXE                   TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

level_3 = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XT                E T  XX",
            "XX      XXXX     XXXX   X",
            "XXX  X  X    XX   X X   X",
            "X       XX    X   X X   X",
            "X XXXXX XXXX     XX X  XX",
            "X       XXXX        X   X",
            "X      XXXXXXX   XXXXX  X",
            "X  X         XXX   E    X",
            "X XXX  XXXXXXXX    XXXX X",
            "X XXXX  XX       XXX    X",
            "X           X     XX  XXX",
            "X XXXXX  XXXX          TX",
            "X X                X XX X",
            "X  TXT     XXX     X  X X",
            "X  XXX  X     P   XX    X",
            "X  XXX  X   XXXX XXX XX X",
            "X  XXX  X   XXXX XXX XX X",
            "X  XXX  X   X     E    TX",
            "XE XXX  XX XX  XXXXX  XXX",
            "XXXXXX  XX     XXXXX  XXX",
            "XXTE    XX  XXX  E     XX",
            "XX XX       XX     X X  X",
            "X E         XX   XXX X TX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]

blank_maze = [
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
           ]